# Runtime: 0.009158134460449219 seconds
# How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
import time
start = time.time()

# Returns number of distinct terms for a^b, for a <= limitA, b <= limitB
def distinctTerms(limitA, limitB):
    terms = []
    for a in range(2, limitA + 1):
        for b in range(2, limitB + 1):
            terms.append(a**b)
    distinct = set(terms)
    return len(distinct)

print(distinctTerms(100, 100))
print(time.time()-start, "seconds")
